alertmanager:
  enabled: false
  ingress:
    enabled: false
grafana:
  enabled: false
prometheus:
  enabled: true
  ingress:
    enabled: false
  prometheusSpec:
    enableRemoteWriteReceiver: true
    externalLabels:
      cluster: testeste-minial-validation-2
    remoteWrite:
    - name: prometheus-otlp-central
      sendExemplars: true
      url: http://54.92.227.240:30002/api/v1/write
    scrapeInterval: 10s
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
prometheusOperator:
  enabled: true
